#!/usr/bin/env bash
# sync-deploy-branch.sh — regenerate `deploy` from current `main` HEAD.
#
# `deploy` is a thin-slice snapshot of main — only the files needed to
# build and run the AWS Lightsail deployment. Everything else (daily
# reports, version history, docs, examples, ref-impl, mpac-package /
# mpac-mcp source, BETA_ACCESS.md, …) stays on main and is NEVER copied
# to deploy. That keeps the deploy branch publishable-looking — anyone
# who clones it gets only what's needed to run the site.
#
# Each run:
#   1. Archives current origin/deploy as deploy-archive-YYYY-MM-DD
#      (idempotent — if today's archive already exists, skip).
#   2. Builds a fresh orphan commit containing only WHITELIST.
#   3. Force-pushes it to origin/deploy. (Old history disappears — it's
#      in the archive branch if you ever need it.)
#
# On Lightsail you pull via `fetch + reset --hard` because deploy
# force-pushes every time — `git pull` would see divergence and refuse.
#
# Run from repo root, on `main`, with no uncommitted changes.
set -euo pipefail

# Only these paths land on the deploy branch. Paths are relative to repo
# root; directories come with all their contents.
WHITELIST=(
    deploy
    web-app
    .dockerignore
    .gitignore
    LICENSE
    README.md
)

log() { printf '\033[1;36m[sync-deploy]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[sync-deploy]\033[0m %s\n' "$*" >&2; exit 1; }

# ── safety gates ──────────────────────────────────────────────────────

[[ -d .git ]] || die "must run from repo root (no .git/ here)"
CURRENT_BRANCH="$(git branch --show-current)"
[[ "$CURRENT_BRANCH" == "main" ]] \
    || die "must run on main — you're on '$CURRENT_BRANCH'"
[[ -z "$(git status --porcelain)" ]] \
    || die "uncommitted changes in working tree — commit or stash first"

MAIN_SHA="$(git rev-parse --short main)"
ARCHIVE="deploy-archive-$(date +%Y-%m-%d)"
REPO_ROOT="$(pwd)"

log "main is at $MAIN_SHA"

# ── 1. Archive the current origin/deploy, if any ─────────────────────

# Fetch the current origin/deploy into a local temp branch so we can see it
# without depending on whether origin/deploy is tracked.
if git ls-remote --exit-code origin deploy >/dev/null 2>&1; then
    git fetch --quiet origin deploy:_sync_old_deploy 2>/dev/null || {
        # If fetch fails because _sync_old_deploy already exists, delete and retry.
        git branch -D _sync_old_deploy 2>/dev/null || true
        git fetch --quiet origin deploy:_sync_old_deploy
    }
    if ! git show-ref --quiet "refs/heads/$ARCHIVE"; then
        git branch "$ARCHIVE" _sync_old_deploy
        git push --quiet origin "$ARCHIVE" || log "(warning: couldn't push $ARCHIVE to origin — archive exists locally only)"
        log "archived old deploy → branch $ARCHIVE (local + origin)"
    else
        log "archive $ARCHIVE already exists; leaving it alone"
    fi
    git branch -D _sync_old_deploy >/dev/null 2>&1 || true
else
    log "no origin/deploy to archive (first sync?)"
fi

# ── 2. Build a fresh orphan commit in a temp worktree ────────────────

TMPDIR="$(mktemp -d -t mpac-deploy-sync-XXXXXX)"
cleanup() {
    # Try graceful worktree removal first; fall back to hard rm.
    git worktree remove --force "$TMPDIR" 2>/dev/null || true
    rm -rf "$TMPDIR"
    git worktree prune >/dev/null 2>&1 || true
    # Drop any leftover temp orphan branch from an interrupted run.
    git branch -D __sync_deploy_fresh >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Clean up leftover state from any previous interrupted run BEFORE we start.
git branch -D __sync_deploy_fresh >/dev/null 2>&1 || true
git worktree prune >/dev/null 2>&1 || true

log "temp worktree: $TMPDIR"
git worktree add --quiet --detach "$TMPDIR" HEAD

(
    cd "$TMPDIR"
    # Orphan — new branch with no parent, fresh history.
    git checkout --quiet --orphan __sync_deploy_fresh
    # Clean slate: un-stage everything, delete every file except .git.
    git rm -rf --cached . >/dev/null 2>&1 || true
    find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

    # Copy each whitelisted path from main.
    for path in "${WHITELIST[@]}"; do
        if git cat-file -e "main:$path" 2>/dev/null; then
            git checkout --quiet main -- "$path"
            log "  + $path"
        else
            log "  - $path (not present in main, skipped)"
        fi
    done

    # Commit. Use a fixed committer identity so the repo's identity isn't
    # required to be set globally.
    git add -A
    git -c user.email="deploy-sync@mpac.local" \
        -c user.name="mpac deploy-sync" \
        commit --quiet -m "deploy: snapshot from main $MAIN_SHA

Auto-generated by deploy/scripts/sync-deploy-branch.sh.
This branch is a thin-slice of main, containing only the files needed
to build and run the AWS Lightsail deployment. For development history
and all other project content, see main.

Included paths:
$(printf '  %s\n' "${WHITELIST[@]}")"

    # Force-push. deploy is a rolling snapshot — old history stays in
    # the archive branch created in step 1.
    git push --force --quiet origin HEAD:deploy
)

log "deploy branch force-pushed from main $MAIN_SHA"
log ""
log "on Lightsail, update with:"
log "  cd ~/Agent_talking"
log "  git fetch origin deploy"
log "  git reset --hard origin/deploy"
log "  sudo docker compose -f deploy/aws-lightsail/docker-compose.yml \\"
log "      --env-file /etc/mpac/compose.env up -d --build"
